### ISSUE TITLE
What is that?

### ISSUE THREAD

**Issue by Streamer272** [ivanhrabcak/DataStructures#1]
I'm browsing through your repositories, and find this. I don't have time to read the whole thing and it doesn't even have a readme.
Please do something about it. 
Thanks

**Comment by ivanhrabcak** [comment]
This repository contains my implementations of some basic data structures (linkedlist, queue, stack), some excercies for other data structures (hashmap, hashset) and some non-working sorting algorithm imlementations.

I can add a README, but I don't think there will be much interest in this repository.
